name: .NET


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
    - name: Restore dependencies
      run: dotnet restore
    - name: Restore NuGet packages
      run: nuget restore EADotnetAngularAddIn\EADotnetAngularAddIn.csproj  -SolutionDirectory .
    - name: Build
      run: dotnet build --no-restore
    - name: Test Cli
      run: dotnet test
    - name: Generate a sample project
      shell: pwsh
      run: | 
        EADotnetAngularCli/bin/Debug/net6.0/EADotnetAngularCli.exe -p "initialize-solution,initialize-angular,db-context,entity,seeder,global-mock-data,app-component,app-routes" -x "data\\Sample\\SampleModel.xml" -n DotnetAngularSample -o DotnetAngularSample -e "Product,Comment" -f
    - name: Test sample project
      run: dotnet test
    - name: Update Angular api
      run: npm run update-api
      working-directory: DotnetAngularSample/DotnetAngularSampleClient
    - name: Build Storybook sample project
      run: npm run build-storybook  --quiet
      working-directory: DotnetAngularSample/DotnetAngularSampleClient
    - name: Serve Storybook and run tests
      run: |
          npx --yes concurrently -k -s first -n "SB,TEST" -c "magenta,blue"  "npx --yes http-server storybook-static --port 6006 --silent" "npx --yes wait-on http://127.0.0.1:6006 && npm run test-storybook"
      working-directory: DotnetAngularSample/DotnetAngularSampleClient
    - name: Build Installer
      run: iscc EADotnetAngularInstaller.iss /F"EADotnetAngularInstaller" 
      working-directory: EADotnetAngularInstaller
    - uses: actions/upload-artifact@v4
      with:
        name: Cli
        path: EADotnetAngularCli/bin/Debug/net6.0/*
    - uses: actions/upload-artifact@v4
      with:
        name: AddIn
        path: EADotnetAngularAddIn/bin/Debug/*
    - uses: actions/upload-artifact@v4
      with:
        name: Installer
        path: |
          EADotnetAngularInstaller/Output/EADotnetAngularInstaller.exe


